[build]
  base = "backend/osdsa/osdsa"
  publish = "target"

[context.production.environment]
  SPRING_DATA_MONGODB_DATABASE = "banking_system_db"
  SPRING_DATA_MONGODB_URI = "mongodb+srv://banking:Ravi-7677@mycosmosmongodbaccount.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
